features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://drupal-logo-2.png'
favicon:
  use_default: 0
  path: 'public://28812870-35257066-76b0-11e7-8e40-dcd6378e06ef.png'
  mimetype: image/png
